#!/bin/sh

# Converts a object file to a C include
# Parameters:
#	$1 - Name of object file

BASE=`basename $1 .o`
INCLUDE=${BASE}.h

cat > ${INCLUDE} <<EOF
/*
 *              DO NOT EDIT THIS FILE !
 * This include file was generated automatically by obj2inc.sh
 * Source file: $1
 */

char ${BASE}[] = {
EOF

# objdump -d $1 | grep -e "^ [0-9a-fA-F]*" | awk '
objdump -d $1 | awk '
BEGIN{ FS="\t"; DELIM="" }
 /^[0-9a-fA-F]+ .*:$/ { print "\n// " $0 }
 /^ [0-9a-fA-F]*/ {
    gsub(/[ \t]+$/,"", $2); 
    gsub(/ /,", 0x", $2); 
    out=sprintf("%s0x%s",DELIM, $2);
    printf("\t%30s\t// %s\n",out,$3);
    DELIM=","
}' >> ${INCLUDE}

echo "};" >> ${INCLUDE}
